// Enhanced Mock Data Store for Testing
import type { Campaign, ContentItem, TopicPillar, RiskAlert, AIAgent, RoadmapItem } from '@/types';

export const mockCampaign: Campaign = {
    id: 'camp_001',
    name: 'Q1 2025 Growth Campaign',
    status: 'active',
    createdAt: new Date('2025-01-01'),
    stats: {
        totalContent: 287,
        publishedThisMonth: 64,
        organicTraffic: 45892,
        trafficGrowth: 47.8,
        avgDwellTime: 189,
        indexationRate: 94,
        riskScore: 8,
    },
    settings: {
        velocity: {
            month1: 15,
            month2: 30,
            month3: 60,
        },
        contentTypes: {
            blog: true,
            youtube: true,
            instagram: true,
            facebook: true,
        },
        autoPublish: false,
        requireApproval: true,
    },
};

export const mockTopicPillars: TopicPillar[] = [
    {
        id: 'pillar_001',
        name: 'Digital Marketing Automation',
        description: 'AI-powered marketing strategies and automation tools',
        keywords: ['marketing automation', 'AI marketing', 'growth hacking', 'lead generation'],
        contentCount: 48,
        priority: 1,
    },
    {
        id: 'pillar_002',
        name: 'SEO Best Practices',
        description: 'Modern SEO techniques and organic growth strategies',
        keywords: ['SEO optimization', 'organic traffic', 'search rankings', 'keyword research'],
        contentCount: 42,
        priority: 2,
    },
    {
        id: 'pillar_003',
        name: 'Social Media Strategy',
        description: 'Content strategies for YouTube, Instagram, TikTok, and LinkedIn',
        keywords: ['social media marketing', 'content strategy', 'engagement', 'viral content'],
        contentCount: 56,
        priority: 3,
    },
    {
        id: 'pillar_004',
        name: 'Content Creation & Optimization',
        description: 'Creating high-quality, engaging content that converts',
        keywords: ['content marketing', 'copywriting', 'conversion optimization', 'A/B testing'],
        contentCount: 38,
        priority: 4,
    },
    {
        id: 'pillar_005',
        name: 'E-commerce Growth',
        description: 'Strategies for scaling online stores and increasing conversions',
        keywords: ['e-commerce SEO', 'product optimization', 'sales funnels', 'Shopify marketing'],
        contentCount: 29,
        priority: 5,
    },
    {
        id: 'pillar_006',
        name: 'Video Marketing',
        description: 'YouTube Shorts, Reels, and TikTok content strategies',
        keywords: ['video marketing', 'YouTube SEO', 'short-form video', 'video editing'],
        contentCount: 34,
        priority: 6,
    },
];

export const mockContentItems: ContentItem[] = [
    {
        id: 'content_001',
        title: '10 AI Tools That Will Transform Your Marketing in 2025',
        type: 'blog',
        status: 'published',
        createdAt: new Date('2025-01-15'),
        publishedAt: new Date('2025-01-16'),
        content: 'Discover the top AI marketing tools revolutionizing how businesses reach their audience. From predictive analytics to automated content generation, these tools are changing the game...',
        metadata: {
            keywords: ['AI marketing', 'marketing tools', 'automation'],
            topicPillar: 'Digital Marketing Automation',
            targetKeyword: 'AI marketing tools 2025',
            seoScore: 96,
            geoScore: 87,
            geoGrade: 'A',
            geoBreakdown: {
                directness: 90,
                authority: 85,
                structure: 92,
                conversational: 78,
                freshness: 95,
                snippetOptimization: 88,
                semanticRichness: 82,
                readability: 86
            },
            geoStrengths: ['✓ Multiple citations', '✓ Excellent use of lists', '✓ Multiple freshness signals'],
            geoRecommendations: ['→ Use more "you" to engage readers'],
            wordCount: 2450,
        },
        performance: {
            views: 8247,
            engagement: 24.5,
            dwellTime: 245,
        },
    },
    {
        id: 'content_002',
        title: 'How to Rank #1 on Google Without Paid Ads',
        type: 'youtube-short',
        status: 'published',
        createdAt: new Date('2025-01-18'),
        publishedAt: new Date('2025-01-20'),
        content: 'Learn the secret SEO strategies that top marketers use to dominate search rankings organically...',
        metadata: {
            keywords: ['SEO ranking', 'organic traffic', 'Google algorithm'],
            topicPillar: 'SEO Best Practices',
            targetKeyword: 'rank on Google',
            seoScore: 92,
            geoScore: 82,
            geoGrade: 'A',
            geoBreakdown: {
                directness: 88,
                authority: 75,
                structure: 85,
                conversational: 82,
                freshness: 80,
                snippetOptimization: 78,
                semanticRichness: 85,
                readability: 83
            },
            geoStrengths: ['✓ Concise opening sentence', '✓ Engaging second-person voice', '✓ Step-by-step format'],
            geoRecommendations: ['→ Add authoritative citations', '→ Include relevant statistics'],
        },
        performance: {
            views: 45892,
            engagement: 8.2,
            dwellTime: 58,
        },
    },
    {
        id: 'content_003',
        title: 'Instagram Reels Algorithm Revealed: 5 Secrets for Viral Content',
        type: 'instagram-reel',
        status: 'published',
        createdAt: new Date('2025-01-19'),
        publishedAt: new Date('2025-01-21'),
        content: 'Unlock the secrets of the Instagram algorithm and create content that goes viral every time...',
        metadata: {
            keywords: ['Instagram algorithm', 'Reels strategy', 'viral content'],
            topicPillar: 'Social Media Strategy',
            targetKeyword: 'Instagram Reels tips',
            seoScore: 89,
            geoScore: 91,
            geoGrade: 'A+',
            geoBreakdown: {
                directness: 95,
                authority: 88,
                structure: 94,
                conversational: 92,
                freshness: 90,
                snippetOptimization: 89,
                semanticRichness: 88,
                readability: 92
            },
            geoStrengths: ['✓ Direct answer in opening', '✓ Data-driven with statistics', '✓ FAQ-style content', '✓ Excellent readability'],
            geoRecommendations: [],
        },
        performance: {
            views: 127450,
            engagement: 12.8,
            dwellTime: 45,
        },
    },
    {
        id: 'content_004',
        title: 'The Ultimate Guide to Programmatic SEO',
        type: 'blog',
        status: 'approved',
        createdAt: new Date('2025-01-20'),
        scheduledFor: new Date('2025-01-25'),
        content: 'Learn how to scale your content production using programmatic SEO techniques that drive massive organic traffic...',
        metadata: {
            keywords: ['programmatic SEO', 'pSEO strategy', 'scale content'],
            topicPillar: 'SEO Best Practices',
            targetKeyword: 'programmatic SEO guide',
            seoScore: 94,
            geoScore: 78,
            geoGrade: 'B',
            geoBreakdown: {
                directness: 75,
                authority: 82,
                structure: 88,
                conversational: 70,
                freshness: 72,
                snippetOptimization: 80,
                semanticRichness: 78,
                readability: 79
            },
            geoStrengths: ['✓ Well-organized with headings', '✓ Includes citations'],
            geoRecommendations: ['→ Consider shortening the opening sentence', '→ Add timeliness context', '→ Use more "you" to engage readers'],
            wordCount: 3200,
        },
    },
    {
        id: 'content_005',
        title: '7 Facebook Marketing Hacks for 2025',
        type: 'facebook-story',
        status: 'pending',
        createdAt: new Date('2025-01-22'),
        content: 'Master Facebook marketing with these proven strategies that boost engagement and drive sales...',
        metadata: {
            keywords: ['Facebook marketing', 'social media ads', 'engagement'],
            topicPillar: 'Social Media Strategy',
            targetKeyword: 'Facebook marketing tips',
            seoScore: 87,
            geoScore: 72,
            geoGrade: 'B',
            geoBreakdown: {
                directness: 70,
                authority: 65,
                structure: 78,
                conversational: 75,
                freshness: 85,
                snippetOptimization: 68,
                semanticRichness: 70,
                readability: 65
            },
            geoStrengths: ['✓ Includes time reference', '✓ Engaging second-person voice'],
            geoRecommendations: ['→ Add authoritative citations', '→ Include relevant statistics', '→ Add section headings'],
        },
    },
    {
        id: 'content_006',
        title: 'AI Content Generation: The Complete 2025 Playbook',
        type: 'blog',
        status: 'published',
        createdAt: new Date('2025-01-10'),
        publishedAt: new Date('2025-01-12'),
        content: 'Everything you need to know about using AI for content creation, from prompts to optimization...',
        metadata: {
            keywords: ['AI content', 'content generation', 'GPT marketing'],
            topicPillar: 'Digital Marketing Automation',
            targetKeyword: 'AI content generation',
            seoScore: 95,
            geoScore: 94,
            geoGrade: 'A+',
            geoBreakdown: {
                directness: 96,
                authority: 92,
                structure: 95,
                conversational: 90,
                freshness: 98,
                snippetOptimization: 93,
                semanticRichness: 92,
                readability: 96
            },
            geoStrengths: ['✓ Direct answer in opening', '✓ Multiple citations', '✓ Excellent use of lists', '✓ Multiple freshness signals', '✓ Excellent readability'],
            geoRecommendations: [],
            wordCount: 4100,
        },
        performance: {
            views: 15420,
            engagement: 28.3,
            dwellTime: 312,
        },
    },
    {
        id: 'content_007',
        title: 'E-commerce SEO: 15 Strategies to Triple Your Sales',
        type: 'blog',
        status: 'published',
        createdAt: new Date('2025-01-08'),
        publishedAt: new Date('2025-01-10'),
        content: 'Comprehensive guide to e-commerce SEO that will help you outrank competitors and boost conversions...',
        metadata: {
            keywords: ['e-commerce SEO', 'online store optimization', 'product pages'],
            topicPillar: 'E-commerce Growth',
            targetKeyword: 'e-commerce SEO strategy',
            seoScore: 93,
            geoScore: 85,
            geoGrade: 'A',
            geoBreakdown: {
                directness: 88,
                authority: 90,
                structure: 92,
                conversational: 80,
                freshness: 78,
                snippetOptimization: 86,
                semanticRichness: 82,
                readability: 84
            },
            geoStrengths: ['✓ Data-driven with statistics', '✓ Key terms emphasized', '✓ Expert references included'],
            geoRecommendations: ['→ Add timeliness context'],
            wordCount: 3800,
        },
        performance: {
            views: 12890,
            engagement: 22.1,
            dwellTime: 278,
        },
    },
    {
        id: 'content_008',
        title: 'TikTok for Business: Complete Marketing Guide',
        type: 'youtube-short',
        status: 'approved',
        createdAt: new Date('2025-01-21'),
        scheduledFor: new Date('2025-01-26'),
        content: 'Learn how to leverage TikTok for business growth with proven strategies...',
        metadata: {
            keywords: ['TikTok marketing', 'short-form video', 'business growth'],
            topicPillar: 'Video Marketing',
            targetKeyword: 'TikTok for business',
            seoScore: 88,
            geoScore: 68,
            geoGrade: 'C',
            geoBreakdown: {
                directness: 65,
                authority: 60,
                structure: 72,
                conversational: 70,
                freshness: 75,
                snippetOptimization: 65,
                semanticRichness: 68,
                readability: 69
            },
            geoStrengths: ['✓ Includes time reference'],
            geoRecommendations: ['→ Consider shortening the opening sentence', '→ Add authoritative citations', '→ Include relevant statistics', '→ Add bullet points or numbered lists'],
        },
    },
    {
        id: 'content_009',
        title: 'LinkedIn Content Strategy That Gets Results',
        type: 'blog',
        status: 'draft',
        createdAt: new Date('2025-01-23'),
        content: 'Build your personal brand and generate leads with a winning LinkedIn content strategy...',
        metadata: {
            keywords: ['LinkedIn marketing', 'B2B content', 'personal branding'],
            topicPillar: 'Social Media Strategy',
            targetKeyword: 'LinkedIn content strategy',
            seoScore: 82,
            wordCount: 2100,
        },
    },
    {
        id: 'content_010',
        title: 'Voice Search SEO: Optimizing for the Future',
        type: 'blog',
        status: 'pending',
        createdAt: new Date('2025-01-24'),
        content: 'Prepare your content for voice search with these optimization techniques...',
        metadata: {
            keywords: ['voice search', 'voice SEO', 'conversational keywords'],
            topicPillar: 'SEO Best Practices',
            targetKeyword: 'voice search optimization',
            seoScore: 86,
            geoScore: 76,
            geoGrade: 'B',
            geoBreakdown: {
                directness: 78,
                authority: 72,
                structure: 80,
                conversational: 85,
                freshness: 70,
                snippetOptimization: 75,
                semanticRichness: 74,
                readability: 74
            },
            geoStrengths: ['✓ Engaging second-person voice', '✓ Interactive with questions'],
            geoRecommendations: ['→ Add timeliness context', '→ Include relevant statistics'],
            wordCount: 1900,
        },
    },
];

export const mockRiskAlerts: RiskAlert[] = [
    {
        id: 'risk_001',
        severity: 'low',
        type: 'indexation',
        message: 'All systems optimal - indexation rate at 94%',
        detectedAt: new Date('2025-01-20'),
        resolved: true,
        recommendation: 'Continue current publishing velocity. Great performance!',
    },
    {
        id: 'risk_002',
        severity: 'low',
        type: 'bounce-rate',
        message: 'Bounce rate improved to 42% (down from 58%)',
        detectedAt: new Date('2025-01-19'),
        resolved: true,
        recommendation: 'Content engagement is excellent. Keep adding interactive elements.',
    },
    {
        id: 'risk_003',
        severity: 'medium',
        type: 'velocity',
        message: 'Approaching velocity threshold - 85% of monthly target reached',
        detectedAt: new Date('2025-01-22'),
        resolved: false,
        recommendation: 'Consider pacing remaining content over the next week to maintain natural growth pattern.',
    },
];

export const mockAIAgents: AIAgent[] = [
    {
        id: 'agent_supervisor',
        name: 'Bedrock Supervisor',
        type: 'supervisor',
        status: 'working',
        lastActive: new Date(),
        tasksCompleted: 1247,
    },
    {
        id: 'agent_seo',
        name: 'SEO Content Worker',
        type: 'seo-worker',
        status: 'working',
        lastActive: new Date(),
        tasksCompleted: 489,
    },
    {
        id: 'agent_social',
        name: 'Social Media Worker',
        type: 'social-worker',
        status: 'working',
        lastActive: new Date(Date.now() - 1000 * 60 * 5),
        tasksCompleted: 376,
    },
    {
        id: 'agent_risk',
        name: 'Risk Monitor',
        type: 'risk-worker',
        status: 'working',
        lastActive: new Date(),
        tasksCompleted: 842,
    },
    {
        id: 'agent_video',
        name: 'Video Content Generator',
        type: 'video-worker',
        status: 'idle',
        lastActive: new Date(Date.now() - 1000 * 60 * 30),
        tasksCompleted: 156,
    },
    {
        id: 'agent_analytics',
        name: 'Analytics Processor',
        type: 'analytics-worker',
        status: 'working',
        lastActive: new Date(),
        tasksCompleted: 2341,
    },
];

export const mockRoadmap: RoadmapItem[] = [
    { week: 1, month: 1, contentTarget: 8, topics: ['Digital Marketing Automation'], status: 'completed' },
    { week: 2, month: 1, contentTarget: 10, topics: ['SEO Best Practices'], status: 'completed' },
    { week: 3, month: 1, contentTarget: 12, topics: ['Social Media Strategy'], status: 'completed' },
    { week: 4, month: 1, contentTarget: 15, topics: ['Content Creation & Optimization', 'E-commerce Growth'], status: 'in-progress' },
    { week: 5, month: 2, contentTarget: 18, topics: ['Digital Marketing Automation', 'SEO Best Practices'], status: 'upcoming' },
    { week: 6, month: 2, contentTarget: 18, topics: ['Social Media Strategy', 'Video Marketing'], status: 'upcoming' },
    { week: 7, month: 2, contentTarget: 20, topics: ['E-commerce Growth'], status: 'upcoming' },
    { week: 8, month: 2, contentTarget: 22, topics: ['All Pillars'], status: 'upcoming' },
    { week: 9, month: 3, contentTarget: 25, topics: ['Digital Marketing Automation', 'SEO Best Practices'], status: 'upcoming' },
    { week: 10, month: 3, contentTarget: 28, topics: ['Social Media Strategy', 'Video Marketing'], status: 'upcoming' },
    { week: 11, month: 3, contentTarget: 30, topics: ['E-commerce Growth', 'Content Optimization'], status: 'upcoming' },
    { week: 12, month: 3, contentTarget: 35, topics: ['All Pillars - Growth Sprint'], status: 'upcoming' },
];

// Platform analytics data
export const mockPlatformAnalytics = {
    wordpress: {
        name: 'WordPress',
        connected: true,
        posts: 89,
        views: 45892,
        growth: 23.5,
        topContent: 'AI Content Generation Playbook',
    },
    youtube: {
        name: 'YouTube',
        connected: true,
        posts: 34,
        views: 127890,
        growth: 67.2,
        topContent: 'SEO Secrets Revealed',
    },
    instagram: {
        name: 'Instagram',
        connected: true,
        posts: 56,
        views: 234567,
        growth: 89.4,
        topContent: 'Reels Algorithm Hack',
    },
    facebook: {
        name: 'Facebook',
        connected: true,
        posts: 42,
        views: 78234,
        growth: 34.8,
        topContent: 'Marketing Tips 2025',
    },
    twitter: {
        name: 'Twitter/X',
        connected: false,
        posts: 0,
        views: 0,
        growth: 0,
        topContent: null,
    },
    linkedin: {
        name: 'LinkedIn',
        connected: false,
        posts: 0,
        views: 0,
        growth: 0,
        topContent: null,
    },
    tiktok: {
        name: 'TikTok',
        connected: false,
        posts: 0,
        views: 0,
        growth: 0,
        topContent: null,
    },
};

// Weekly performance data for charts
export const mockWeeklyPerformance = [
    { week: 'Week 1', traffic: 8420, content: 8, engagement: 4.2 },
    { week: 'Week 2', traffic: 12890, content: 10, engagement: 5.8 },
    { week: 'Week 3', traffic: 18450, content: 12, engagement: 7.2 },
    { week: 'Week 4', traffic: 28670, content: 15, engagement: 9.1 },
    { week: 'Week 5', traffic: 38920, content: 18, engagement: 11.4 },
    { week: 'Week 6', traffic: 45892, content: 21, engagement: 13.8 },
];
